# Generated by Django 4.1.7 on 2023-03-31 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ports',
            fields=[
                ('code', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'ports',
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('slug', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('parent_slug', models.ForeignKey(blank=True, db_column='parent_slug', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ratestask.regions')),
            ],
            options={
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('price', models.IntegerField()),
                ('dest_code', models.ForeignKey(db_column='dest_code', default='some', on_delete=django.db.models.deletion.DO_NOTHING, related_name='destination_port_code', to='ratestask.ports')),
                ('orig_code', models.ForeignKey(db_column='orig_code', default='some', on_delete=django.db.models.deletion.DO_NOTHING, related_name='origin_port_code', to='ratestask.ports')),
            ],
            options={
                'db_table': 'prices',
            },
        ),
        migrations.AddField(
            model_name='ports',
            name='parent_slug',
            field=models.ForeignKey(db_column='parent_slug', on_delete=django.db.models.deletion.DO_NOTHING, to='ratestask.regions'),
        ),
    ]
